import { IUserData } from '../../model/Interface/IUserData';


export const mockUserData: IUserData = {
  id: 1,
  username: 'Sophia Miller',
  email: 'sophia.miller@example.com',
  biography: 'Passionate about art and design.',
  lastSeen: '2 minutes ago',
  photo: $r('app.media.pic1')
};

export const mockUserData2: IUserData = {
  id: 2,
  username: 'Jackson Davis',
  email: 'jackson.davis@example.com',
  biography: 'Loves coding and gaming.',
  lastSeen: '18 minutes ago',
  photo: $r('app.media.pic2')
};

export const mockUserData3: IUserData = {
  id: 3,
  username: 'Olivia Wilson',
  email: 'olivia.wilson@example.com',
  biography: 'Exploring new cultures and cuisines.',
  lastSeen: '1 hour ago',
  photo: $r('app.media.pic3')
};


export const mockUser4: IUserData = {
  id: 4,
  username: 'William Brown',
  email: 'william.brown@example.com',
  biography: 'Dedicated to fitness and healthy living.',
  lastSeen: '7 minutes ago',
  photo: '$r(app.media.william_profile)'
};

export const mockUser5: IUserData = {
  id: 5,
  username: 'Ava Garcia',
  email: 'ava.garcia@example.com',
  biography: 'Enjoys reading and writing.',
  lastSeen: '35 minutes ago',
  photo: '$r(app.media.ava_profile)'
};

export const mockUser6: IUserData = {
  id: 6,
  username: 'James Rodriguez',
  email: 'james.rodriguez@example.com',
  biography: 'Music lover and aspiring musician.',
  lastSeen: '22 minutes ago',
  photo: '$r(app.media.james_profile)'
};

export const mockUser7: IUserData = {
  id: 7,
  username: 'Isabella Martinez',
  email: 'isabella.martinez@example.com',
  biography: 'Traveling and photography enthusiast.',
  lastSeen: '55 minutes ago',
  photo: '$r(app.media.isabella_profile)'
};

export const mockUser8: IUserData = {
  id: 8,
  username: 'Benjamin Anderson',
  email: 'benjamin.anderson@example.com',
  biography: 'Science and technology geek.',
  lastSeen: '12 minutes ago',
  photo: '$r(app.media.benjamin_profile)'
};

export const mockUser9: IUserData = {
  id: 9,
  username: 'Mia Thomas',
  email: 'mia.thomas@example.com',
  biography: 'Nature lover and environmental advocate.',
  lastSeen: '40 minutes ago',
  photo: '$r(app.media.mia_profile)'
};

export const mockUser10: IUserData = {
  id: 10,
  username: 'Ethan Jackson',
  email: 'ethan.jackson@example.com',
  biography: 'Sports fanatic and team player.',
  lastSeen: '28 minutes ago',
  photo: '$r(app.media.ethan_profile)'
};
