import { router } from '@kit.ArkUI';

export function routePageNoParams(url: string) {
  let options:router.RouterOptions = {
    url: url,
  }
  try {
    router.pushUrl(options, router.RouterMode.Single)
  } catch (err) {
  }
}

export function routePageWithParams(url: string, param1: string) {
  let options:router.RouterOptions = {
    url: url,
    params: param1
  }
  try {
    router.pushUrl(options, router.RouterMode.Single)
  } catch (err) {
  }
}

export function routePageWithObjectParams(url: string, params: object) {
  let options:router.RouterOptions = {
    url: url,
    params: params
  }
  try {
    router.pushUrl(options, router.RouterMode.Single)
  } catch (err) {
  }
}

export function getParams() {
  let params: object = router.getParams()
  try {
    return params
  } catch (err) {
    return undefined
  }
}

export function clearBackstack(){
  router.clear()
}

export function routerBack(){
  router.back()
}
